name: Create Release

on: workflow_dispatch

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Get version from manifest
        id: get_version
        run: |
          VERSION=$(jq -r .version manifest.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Create zip file
        run: zip -r figma_non_dev_alert.zip . -x "*.git*"

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ steps.get_version.outputs.VERSION }} \
            --title "v${{ steps.get_version.outputs.VERSION }}" \
            --target ${{ github.ref_name }} \
            --generate-notes \
            --draft \
            figma_non_dev_alert.zip
