name: Create Release

on: workflow_dispatch

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
